twig:
    default_path: '%kernel.project_dir%/templates'
    # para añadir un estilo de bootstrap a los formularios
    form_themes: 
       - 'bootstrap_5_layout.html.twig'


when@test:
    twig:
        strict_variables: true
